// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gcceplgwujpcymiapbrb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjY2VwbGd3dWpwY3ltaWFwYnJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NjQwMTQsImV4cCI6MjA2ODU0MDAxNH0.W_gnJxfaBrrvbVZgtHGnQrxZyI7OWrzVf06gAeJeGbk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});